on:
  pull_request:
    branches:
      - v8
name: Check version commit message
jobs:
  checkVersionCommit:
    name: Check connect version commit message
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          LAST_COMMIT=$(git log -1 --pretty=%B)
          VERSION=$(jq -r .version package.json)
          [[ "$LAST_COMMIT" == "version $VERSION" ]]
